# Change Default `send-prefix` keybinding to C-a (Nullify C-b)
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set Vim-like Scroll Options
setw -g mode-keys vi
set  -g status-keys vi

# Use Mouse
setw -g mouse on

# Minimum delay for escape key press
#   (Any lower value may input garbage chars to tmux session)
set -sg escape-time 40

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Shift-(vim keys) to switch windows -> Just trying out
bind -n S-h previous-window
bind -n S-l next-window

# Set 256-color compatible terminal -> Needs `-2` flag on startup
set -g default-terminal "screen-256color"

# NOTE: WSL-specific settings for clipboard!
# bind -n M-w run -b "tmux show-buffer | clip.exe"
bind C-c run -b "tmux show-buffer | clip.exe"

# Split Panes Vertically and Horizontally
bind H split-window -h
bind V split-window -v
bind | split-window -hf
bind _ split-window -vf

# Plugins {

## TPM (Tmux Plugin Manager) {
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

## } Tmux Battery {
set -g status-right '#{battery_status_bg}  #{battery_percentage}% | %H:%M, %d %h. (%a)'
### NOTE: If able, use conditional variable to change battery icon based on current status

## }

# }

## Initialise TPM (NOTE: Keep at End of File!)
run '~/.tmux/plugins/tpm/tpm'
